using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace E_Commerce.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {
        protected override void Seed(DataContext context)
        {
            var kategoriler = new List<Category>()
            {
                new Category(){Name = "Electronic", Description = "Electronic Products"},
                new Category(){Name = "Fashion", Description = "Fashion Products"},
                new Category(){Name = "Home,Life", Description = "Home,Life Products"},
                new Category(){Name = "Sport,Outdoor", Description = "Sport,Outdoor Products"},
                new Category(){Name = "Cosmetics,Personal Care", Description = "Cosmetics,Personal CareProducts"},
                new Category(){Name = "Book,Music.Movie", Description = "Book,Music.Movie CareProducts"}
            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            var urunler = new List<Product>()
            {
                new Product(){ Name = "Iphone 14 Pro 128 GB", Description = "iOS 16, Kilit Ekranı’nızı yepyeni ve eğlenceli yollarla kişiselleştirmenize imkan sağlıyor. Daha dikkat çekici olması için fotoğrafınızı öne çıkarın. Aktivite halkalarınızı takip edin. Ve sevdiğiniz uygulamalardan gelen gerçek zamanlı güncellemeleri görün.",Image="https://productimages.hepsiburada.net/s/283/550/110000271395200.jpg", Price =42999 , ProductAvailable =true , CategoryId = 1,IsHome = true ,Brand="Apple",Type="Telefon" },
                new Product(){ Name = "Iphone 12 128 GB", Description = "Hızını anlatmaya kelimeler yetişemez. Bir akıllı telefondaki en hızlı çip olan A14 Bionic. Kenarlara kadar uzanan OLED ekran. Ve artık tüm kameralarda yer alan Gece modu.Gözünüze de hitap ediyor, elinize de. İnanılmaz kontrast ve daha yüksek çözünürlük sunan, bugüne kadarki en iyi iPhone ekranı. Ve düşmelere karşı 4 kat daha iyi bir performans sergileyen Ceramic Shield.◊",Image="https://productimages.hepsiburada.net/s/189/550/110000155170588.jpg", Price =19999 , ProductAvailable =true , CategoryId = 1,IsHome = true,Brand="Apple",Type="Telefon"},
                new Product(){ Name = "Iphone 14 256 GB", Description = "Profesyonel seviyedeki yeni Ana kamera ve daha iyi görüntü işleme sayesinde her türlü aydınlatma düzeyinde, özellikle de loş ışıkta daha da muhteşem görünen fotoğraflar çekebiliyorsunuz.iPhone 14, ciddi bir araba kazası geçirirseniz bunu algılayarak 112’yi arıyor ve acil durum kişilerinize haber veriyor.",Image="https://productimages.hepsiburada.net/s/280/550/110000267190501.jpg", Price =34399 , ProductAvailable =false , CategoryId = 1,IsHome = true,Brand="Apple",Type="Telefon"},
                new Product(){ Name = "Iphone 13 128 GB",Description="Süper bir güç.Süper parlak bir ekran ve dayanıklı tasarım. Filmleri aratmayan, kolay video çekimleri. Işık hızında bir çip. Ve hayatınızda fark yaratan çok daha uzun pil ömrü.",Image="https://productimages.hepsiburada.net/s/189/550/110000155170675.jpg",Price =24999 , ProductAvailable =true , CategoryId = 1,IsHome = true,Brand="Apple",Type="Telefon"},
                new Product(){ Name = "Samsung Z-Flip4", Description = "Katlanabilir telefon piyasası içerisinde dikkatleri üzerinde toplayan Z Flip serisi, şık tasarımı ve etkileyici teknik detaylarıyla kullanıcılarına farklı bir dünyanın kapılarını açar. Geçmiş zamanın nostaljik esintilerini taşıyan katlanabilir tasarım, cihazınızı her yere rahat bir şekilde sığdırmanızı sağlar. Pantolonunuzun cebine ya da çantanıza kolaylıkla yerleştirebilir, alan problemi yaşamadan geniş ekranın keyfini çıkarmaya başlayabilirsiniz. Samsung Galaxy Z Flip4 128 GB 8 GB RAM (Samsung Türkiye Garantili) kamera detaylarıyla da kullanıcılarına avantajlar sunmaya devam eder. Yüksek çözünürlükle desteklenen geniş diyafram aralığı sayesinde ortamın ışığı fark etmeksizin her yerde net görseller elde etmenizi kolaylaştırır..",Image="https://productimages.hepsiburada.net/s/266/550/110000251246224.jpg", Price =20722  , ProductAvailable =false , CategoryId = 1,Brand="Samsung",Type="Telefon"},
                new Product(){ Name = "Samsung S22 Ultra", Description = "Akıllı telefon sektörünün lider markası Samsung’un sunduğu Samsung Galaxy S22 Ultra 5G 128 GB (Samsung Türkiye Garantili), premium akıllı telefon kategorisinde şimdiye kadar geliştirilen en güçlü cihaz olma özelliğine sahiptir. Galaxy Note serisinin yüksek performansını ve Galaxy S serisinin profesyonel kamera özelliklerini bünyesinde toplayan Samsung Galaxy S22 Ultra 5G modeli, Samsung’un yeni amiral gemisi olarak üst segmentte yer alır.",Image="https://productimages.hepsiburada.net/s/178/550/110000142781614.jpg", Price =21998  , ProductAvailable =false , CategoryId = 1,Brand="Samsung",Type="Telefon"},
                new Product(){ Name = "Samsung Note 22 Ultra", Description = "Note20 Ultra, hem trend hem de zamanın ötesinde tasarımıyla dikkat çekiyor. Nefes kesici mistik renklere sahip olan model, zarif detaylarla zenginleştirilmiş metal bir yapı ile öne çıkıyor. Minimal bir tasarıma sahip olan telefonun ekranı Corning® Gorilla® Glass Victus™ ile korunuyor.",Image="https://productimages.hepsiburada.net/s/41/550/10698989043762.jpg", Price =18499, ProductAvailable =false , CategoryId = 1,IsHome =false,Brand="Samsung",Type="Telefon"},

                //Kamera
                new Product(){ Name = "Canon EOS-440 E", Description = "İster şık ve taşınabilir şipşak fotoğraf makinesi modelleri ve hafif, sabit lens esnekliği sunan kompakt fotoğraf makineleri ister son teknoloji özellikler sunan DSLR'lar ve aynasız fotoğraf makineleri olsun Canon'un fotoğraf makinesi serisi herkesin yaratıcılığına hitap eder.",Image="https://productimages.hepsiburada.net/s/19/550/9853227532338.jpg", Price =7899  , ProductAvailable =true , CategoryId = 1 ,Brand="Canon" ,Type="Kamera" },
                new Product(){ Name = "Canon EOS-1200 D",Description="Kullanmayı çok seveceğiniz ergonomik tasarım Optik vizör, çekiminizi oluşturmanıza ve tahmin etmenize olanak tanıyarak her zaman anın arkasındaki duyguyu yakalamak için hazır olmanızı sağlar. Sezgisel kullanımlı kullanıcı dostu kontrolleri ve görüntüyü incelemek için 7,5 cm'lik (3 inç) geniş LCD ekranıyla EOS 1200D'yi kullanması çok keyiflidir.",Image="https://productimages.hepsiburada.net/s/90/550/110000033268534.jpg", Price =10899  , ProductAvailable =true , CategoryId = 1,Brand="Canon" ,Type="Kamera"},
                new Product(){ Name = "Canon EOS R5", Description = "Aynasız fotoğraf makineleri hakkında bildiklerinizi bir kez daha gözden geçirin. EOS R5'in ödün vermeyen performansı, fotoğraf ve video çekimlerinize yepyeni bir yaklaşım getirecek.",Image="https://productimages.hepsiburada.net/s/20/550/9871523545138.jpg", Price =3689  , ProductAvailable =true , CategoryId = 1,Brand="Canon" ,Type="Kamera"},
                new Product(){ Name = "ZAF 105M", Description = "ZAF105 180 derece diyagonal görüş açısı.Süper çok kaplama.Parlama ve hayalet minimum odak.Mesafe 12 inç çıkarılabilir.Manuel odaklama.Petal lens kapağı.Asferik dairesel ultra balıkgözü lens",Image="https://productimages.hepsiburada.net/s/354/550/110000363164283.jpg", Price =1699  , ProductAvailable =true , CategoryId = 1,Brand="ZAF" ,Type="Kamera"},
                new Product(){ Name = "Xiaomi Mijia", Description = "IP65 suya dayanıklılık IP65 sınıfı suya ve toza dayanıklı tasarım, olumsuz çevresel faktörlerde bile kullanılabilir.Manyetik yapı Hızlı kurulum, manyetik tabanı ve kendinden yapışkanlı yüzeyi ile her yere yerleştirmesi kolaydır.Küresel gövde ve manyetik taban sayesinde kolayca ayarlanabilen görüş açısı.",Image="https://productimages.hepsiburada.net/s/23/550/10051049422898.jpg", Price =3699, ProductAvailable =true , CategoryId = 1,Brand="Xiaomi" ,Type="Kamera"},
                new Product(){ Name = "Fujifilm Instax Mini 11", Description = "Instax mini 11, manuel ayarlamaya gerek olmadan çevredeki ışığı otomatik olarak algılayıp, deklanşör hızını ışığa göre ayarlar. Otomatik ışık ayarı ve yüksek performanslı flaş ışığı sayesinde, ışığın sadece yakın mesafeyi değil arka planı da aydınlatmasını sağlar.",Image="https://productimages.hepsiburada.net/s/274/550/110000259904685.jpg", Price =1869  , ProductAvailable =true , CategoryId = 1,Brand="Fujifilm" ,Type="Kamera"},
                new Product(){ Name = "Fujifilm Instax Evo", Description = "Instax Mini Evo Siyah Fotoğraf Makinesi ve 10lu Film Instax Mini Evo Siyah Fotoğraf Makinesi hibrit yanin hem dijital hem de analog bir fotoğraf makinesidir Instax hibrit fotoğraf makinelerinin en yeni üyesi olan mini Evo keyifli ve eğlenceli birçok özelliğe sahiptir Anında Fotoğraf Çek ve BastırSetin içinde instax mini Evo Fotoğraf Makinesi ile birlikte 10lu instax mini film de yer alıyor.",Image="https://productimages.hepsiburada.net/s/261/550/110000244551943.jpg", Price =8900  , ProductAvailable =false , CategoryId = 1,Brand="Fujifilm" ,Type="Kamera"},

                //Bilgisayar
                new Product(){ Name = "Monster Abra A5 V17.2.3 Intel Core i5-11400H 16GB RAM 500GB SSD 4GB RTX3050Ti", Description = "OYUNDA KENDİNİZİ KAYBETSENİZ BİLE! Monster Oyun Bilgisayarları Intel ve Nvidia’nın en üst donanımları ile, maksimum performans ve en mükemmel oyun deneyimini sunar. Kendi belirleyeceğiniz donanımlar ve oynadığınız oyunların gereksinimlerine göre hayalinizdeki bilgisayarı şimdi tasarlayın!",Image="https://productimages.hepsiburada.net/s/274/550/110000260906928.jpg", Price =20899  , ProductAvailable =true , CategoryId = 1,Brand="Monster" ,Type="Bilgisayar"},
                new Product(){ Name = "Asus ROG Strix G513IC-HN037 AMD Ryzen 7 4800H 16GB 512GB SSD RTX3050",Description="ASUS ROG Strix, size süper hızlı bir veri performansı ve geniş depolama kapasitesinin avantajlarını sağlamak için çift depolama tasarımınlı opsiyona sahiptir. Daha hızlı yanıt ve yükleme süreleri için uygulamaları SSD'ye yükleyin ve HDD'yi filmler, müzik kitaplıkları ve fotoğraf albümleri gibi büyük dosyaları depolamak için kullanın.",Image="https://productimages.hepsiburada.net/s/205/550/110000180001405.jpg", Price =19699  , ProductAvailable =true , CategoryId = 1,Brand="Asus" ,Type="Bilgisayar"},
                new Product(){ Name = "Apple MacBook Pro M2 Çip 16 GB 512 GB SSD 13.6",Description="Her Mac’te, daha verimli bir şekilde araştırma yapmanıza, iletişim kurmanıza ve çalışmanıza yardımcı olacak birbirinden güçlü yaratıcılık ve üretkenlik uygulamaları bulunur.Yaratıcılıklarını bir adım ileriye taşımak isteyen profesyonellerin müzik ve film düzenleme, işleme ve yayınlama aşamalarının tümü üzerinde maksimum kontrole sahip olmalarını sağlayan uygulamalar.",Image="https://productimages.hepsiburada.net/s/337/550/110000314161726.jpg", Price =39499  , ProductAvailable =true , CategoryId = 1,Brand="Apple" ,Type="Bilgisayar"},
                new Product(){ Name = "Asus X415JA-EK1754 Intel Core i5 1035G1 8GB 256GB SSD",Description="ASUS Studiobook serisi, fikirleri hayata geçiren güçlü bir güç merkezidir. NVIDIA® Quadro GPU'ya sahiptir ve sürükleyici görseller için ince çerçeveli NanoEdge ekrana sahiptir. Son teknoloji grafikler ve taşınabilirlik kombinasyonu, onu yaratıcı profesyoneller için mükemmel kılar.",Image="https://productimages.hepsiburada.net/s/206/550/110000182821026.jpg", Price =21499  , ProductAvailable =true , CategoryId = 1,Brand="Asus" ,Type="Bilgisayar"},
                new Product(){ Name = "Dell Gaming G15 5520 Intel Core i7 12700H 16GB 512GB SSD RTX3050Ti",Description="Esnek, Ölçeklenebilir BT Çözümleri İş ihtiyaçlarınıza uyum ve ölçekleyen sunucu, depolama ve ağ çözümleriyle güç dönüşümü",Image="https://productimages.hepsiburada.net/s/231/550/110000212933277.jpg", Price =17499  , ProductAvailable =true , CategoryId = 1,Brand="Dell" ,Type="Bilgisayar"},
                new Product(){ Name = "Asus X515EA-BQ1184 Intel Core i7 1165G7 8 GB 512 GB SSD",Description="Yaratıcı gücünüzü açığa çıkaran ASUS Zenbook serisi size gerçek yaratıcılığı ortaya çıkarmanız için araçlar sunar. Ultra hızlı performansı hassas işlenmiş zarafetle birleştiren Zenbook, yaratıcı potansiyelinizi sınırsızca en üst düzeye çıkarmanızı sağlar.",Image="https://productimages.hepsiburada.net/s/340/550/110000346391529.jpg", Price =15499  , ProductAvailable =true , CategoryId = 1,Brand="Asus" ,Type="Bilgisayar"},
                new Product(){ Name = "DELL Gaming G5 15 G55201800U Intel Core i7-12700H 16GB 512GB SSD RTX3060",Description="Gerçek hayattaki gibi iletişim kurun Kamera yenilikleri, çarpıcı çözünürlük sağlarken düşük ışıkta keskin görseller sağlar. Endüstrinin ilk SafeShutter  web kamerası otomatik açılır/kapanır ve güvenli kamera ve mikrofon kapatma tuşlarıyla tam denetim sunar. Akıllı ses, ses kalitenizi artırır ve arka plan seslerini azaltır.",Image="https://productimages.hepsiburada.net/s/286/550/110000274801619.jpg", Price =24499  , ProductAvailable =true , CategoryId = 1,Brand="Dell" ,Type="Bilgisayar"},
                new Product(){ Name = "Monster Tulpar V19.2.5 Intel Core i5-12500H 16GB RAM 500GB SSD 4GB RTX3050Ti",Description="En yüksek performanslı notebook modellerini, en erişilebilir fiyatlarla kullanıcılarla buluşturan Monster, yılların verdiği sektör tecrübesiyle ürün gamını şekillendirerek tüm ihtiyaçlarınıza uygun notebook modelleri hazırlıyor",Image="https://productimages.hepsiburada.net/s/267/550/110000252781234.jpg", Price =26999  , ProductAvailable =false , CategoryId = 1,Brand="Monster" ,Type="Bilgisayar"},

                //Tablet bilgisayar
                new Product(){ Name = "Apple iPad 9. Nesil 64GB 10.2", Description = "Yaşamınızın her alanında son teknoloji özelliklerden faydalanmak istiyorsanız iPad 9.Nesil tablet tam size göre! Şık tasarımı ve fonksiyonel özellikleriyle öne çıkan ürün farklı kullanım alanlarına hitap edebiliyor.",Image="https://productimages.hepsiburada.net/s/276/550/110000262088812.jpg", Price =10699  , ProductAvailable =true , CategoryId = 1,Brand="Apple" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Lenovo Tab M10 (3rd Gen) 4gb 64 GB", Description = "En sevdiğiniz eğlenceler aynı çatı altında.Ana ekranınızdan sağ tarafa kayarak Entertainment Space üzerinden yeni içerikler keşfedebilirsiniz. Üyelik bilgilerinizi girerek filmlerden televizyon dizilerine, oyunlardan kitaplara, en sevdiğiniz eğlence kaynaklarına kişiselleştirilmiş erişim sağlayabilirsiniz. Üstelik hepsi aynı çatıda olduğu için, uygulamadan uygulamaya atlamanıza da gerek kalmaz.",Image="https://productimages.hepsiburada.net/s/276/550/110000262088812.jpg", Price =7499  , ProductAvailable =true , CategoryId = 1,Brand="Lenovo" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Samsung Galaxy Tab A8 SM-X200 3GB 32GB", Description = "10.5 genişliğindeki ekranını tamamlayan simetrik çerçevesi yalnızca 10.2 mm’dir; böylece ekrandaki görüntü sizi tamamen sarar. Keşfetmeye sınırları zorlayarak devam edin.Efsaneleşmiş filmlerden hobinizle ilgili nasıl yapılır videolarına, Galaxy Tab A8 daha büyük ve daha iyi bir görüntüyle sizi daha geniş bir dünyaya davet ediyor.",Image="https://productimages.hepsiburada.net/s/203/550/110000177118127.jpg", Price =3699  , ProductAvailable =true , CategoryId = 1,Brand="Samsung" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Lenovo Tab M10 Plus TB-X606F", Description = "Dolby Atmos® teknolojisine sahip üstün JBL dörtlü hoparlör sistemi sayesinde tüm ses ve notaları adeta tiyatro ya da stadyumdaymışçasına duyarsınız. Bas güçlendirme ve ses doğruluğu gibi özelliklere sahip olan ve Lenovo Premium Ses tasarımı ve optimizasyonuyla desteklenen bu sistem ile kristal netliğinde sesli aramalar yapabilirsiniz.",Image="https://productimages.hepsiburada.net/s/42/550/10748773531698.jpg", Price =7899  , ProductAvailable =true , CategoryId = 1,Brand="Lenovo" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Apple iPad 10.Nesil 64GB", Description = "iPad çok yönlü bir aygıt. Bu yüzden her türlü göreve her zaman hazır. Bir proje üzerinde çalışın, yaratıcılığınızı ifade edin veya sürükleyici bir oyun oynayın. Ne yapıyor olursanız olun, iPad tümünü eğlenceli ve güçlü bir şekilde yapabilmeniz için yanınızda. İşte iPad ile yapabileceğiniz sayısız şeyden sadece birkaçı.",Image="https://productimages.hepsiburada.net/s/337/550/110000294957843.jpg/format:webp", Price =12699  , ProductAvailable =true , CategoryId = 1,Brand="Apple" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Samsung Galaxy Tab S8+ SM-X800 128GB", Description = "Samsung Galaxy Tab S8 gümüş tablet, size üst düzey bir tablet deneyimi yaşatmak üzere burada beğeninize sunuluyor. Geniş ekran, ultra geniş açılı ön kamera, S Pen desteği ve güçlü bataryası ile tam bir kurtarıcı olan Samsung Galaxy Tab S8+.",Image="https://productimages.hepsiburada.net/s/178/550/110000142699063.jpg", Price =15299  , ProductAvailable =true , CategoryId = 1,Brand="Samsung" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Apple iPad Pro 5. Nesil Wi-Fi 128 GB", Description = "Mobil bir güç merkezine dönüşen iPad Pro ile oyun oynamanın tadını çıkarmak kalıyor. Güçlü uygulamaları ve yoğun grafiklere sahip oyunları aynı anda kusursuz bir şekilde çalıştırın. Ve M1 çip sayesinde SketchUp gibi uygulamalarda yaratıcılığınızın sınırlarını.",Image="https://productimages.hepsiburada.net/s/74/550/110000016334848.jpg", Price =22699  , ProductAvailable =true , CategoryId = 1,Brand="Apple" ,Type="Tablet Bilgisayar"},
                new Product(){ Name = "Lenovo Yoga Tab 11 YT-J706F 4GB 128GB", Description = "Lenovo Yoga Tab 11 ile kendinizi sinema salonundaymış gibi hissedin. Dolby Vision™ özellikli ve TÜV düşük mavi ışık sertifikalı 2K ekranı tam bir zarafet örneği. Bu ekrana, Dolby Atmos® teknolojisini Lenovo Premium Ses Sistemi ile buluşturan dörtlü JBL hoparlörleri de ekleyince, küçük bir salonda kendi sinemanızı yaratmış oluyorsunuz",Image="https://productimages.hepsiburada.net/s/229/550/110000210642308.jpg", Price =5399 , ProductAvailable =true , CategoryId = 1,Brand="Lenovo" ,Type="Tablet Bilgisayar"},
                //////////////////////////////////////////////// Categori 2
                //Elbise

                new Product(){ Name = "Koton Maxi Elbise ",Description="",Image="https://productimages.hepsiburada.net/s/308/600-800/110000300945712.jpg", Price =899 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Elbise",Brand="Koton"},
                new Product(){ Name = "Koton Etnik Nakışlı Mini Elbise Balon Kollu",Description="",Image="https://productimages.hepsiburada.net/s/286/600-800/110000275239919.jpg", Price =189 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Elbise",Brand="Koton"},
                new Product(){ Name = "Koton Maxi Elbise Püskül Detaylı Beli Kuşaklı",Description="",Image="https://productimages.hepsiburada.net/s/318/600-800/110000312479380.jpg", Price =649 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Elbise",Brand="Koton"},
                new Product(){ Name = "Koton Mini Gömlek Elbise Kolsuz",Description="",Image="https://productimages.hepsiburada.net/s/230/600-800/110000212286288.jpg", Price =429, ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Elbise",Brand="Koton"},
                new Product(){ Name = "Koton Midi Boy Gömlek Elbise Keten Karışımlı",Description="",Image="https://productimages.hepsiburada.net/s/286/600-800/110000274826836.jpg", Price =599 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Elbise",Brand="Koton"},
                new Product(){ Name = "U.S. Polo Assn. Kadın Taş Melanj Triko Elbise",Description="",Image="https://productimages.hepsiburada.net/s/335/300-400/110000340462135.jpg", Price =789 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Elbise",Brand="U.S. Polo Assn."},
                new Product(){ Name = "U.S. Polo Assn. Kadın Antrasit Melanj Triko Elbise",Description="",Image="https://productimages.hepsiburada.net/s/335/600-800/110000340460536.jpg", Price =624 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Elbise",Brand="U.S. Polo Assn."},
                new Product(){ Name = "U.S. Polo Assn. %100 Pamuk Kısa Kol Elbise",Description="",Image="https://productimages.hepsiburada.net/s/343/600-800/110000350584123.jpg", Price =599 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Elbise",Brand="U.S. Polo Assn."},
                new Product(){ Name = "U.S. Polo Assn. Kadın Lacivert Örme Elbise",Description="",Image="https://productimages.hepsiburada.net/s/271/600-800/110000256979207.jpg", Price =879 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Elbise",Brand="U.S. Polo Assn."},
               //T-Shirt
               
                new Product(){ Name = "Koton Uzun Kollu Baskılı Tişört Bisiklet Yaka Pamuklu",Description="",Image="https://productimages.hepsiburada.net/s/350/600-800/110000358101100.jpg", Price =120 , ProductAvailable =false,IsHome=false , CategoryId = 2,Type="T-Shirt",Brand="Koton"},
                new Product(){ Name = "Vitrin V Yaka Kısa Kol Pamuk T-Shirt",Description="",Image="https://productimages.hepsiburada.net/s/174/600-800/110000137093569.jpg", Price =149 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="T-Shirt",Brand="Koton"},
                new Product(){ Name = "Mavi Kadın Miav Baskılı Beyaz Tişört",Description="",Image="https://productimages.hepsiburada.net/s/169/600-800/110000131629890.jpg", Price =299 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="T-Shirt",Brand="Mavi"},
                new Product(){ Name = "Mavi Erkek Mavi Logo Baskılı Kırmızı Tişört",Description="",Image="https://productimages.hepsiburada.net/s/68/600-800/110000009631891.jpg", Price =229 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="T-Shirt",Brand="Mavi"},
                new Product(){ Name = "Mavi Volume Baskılı Sarı Tişört",Description="",Image="https://productimages.hepsiburada.net/s/289/600-800/110000277615599.jpg", Price =229 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="T-Shirt",Brand="Mavi"},
                new Product(){ Name = "DeFacto Fit NBA Golden State Warriors Boxy Fit Bisiklet Yaka Tişört ",Description="",Image="https://productimages.hepsiburada.net/s/267/600-800/110000252016771.jpg", Price =189 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="T-Shirt",Brand="Defacto"},
                new Product(){ Name = "U.S. Polo Assn. Kadın Lacivert T-Shirt",Description="",Image="https://productimages.hepsiburada.net/s/240/600-800/110000224478635.jpg", Price =179 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="T-Shirt",Brand="U.S. Polo Assn."},
                new Product(){ Name = "DeFacto Traditional Bisiklet Yaka Kelebek Desenli Kısa Kollu Tişört",Description="",Image="https://productimages.hepsiburada.net/s/286/600-800/110000275137924.jpg", Price =209 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="T-Shirt",Brand="Defacto"},
                new Product(){ Name = "Mavi Kadın Üçgen Baskılı Beyaz İstanbul Tişört ",Description="",Image="https://productimages.hepsiburada.net/s/68/600-800/110000009633591.jpg", Price =199 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="T-Shirt",Brand="Mavi"},
                //Ayakkabı

                new Product(){ Name = "Puma 373017 - 01 Unisex Günlük Spor Ayakkab",Description="",Image="https://productimages.hepsiburada.net/s/44/600-800/10789308268594.jpg", Price =1299 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Puma"},
                new Product(){ Name = "Skechers Summits Kadın Spor Ayakkabı 12980TK BBK",Description="",Image="https://productimages.hepsiburada.net/s/169/600-800/110000132077655.jpg", Price =2410, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Skechers"},
                new Product(){ Name = "Skechers Solar Fuse Kadın Ayakkabı 13325-Bkw",Description="",Image="https://productimages.hepsiburada.net/s/43/600-800/10764605227058.jpg", Price =1459 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Ayakkabı",Brand="Skechers"},
                new Product(){ Name = "Skechers BOUNTİFUL - BRİSK STRİDE Kadın Lacivert Spor Ayakkabı ",Description="",Image="https://productimages.hepsiburada.net/s/136/600-800/110000087854966.jpg", Price =1499 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Skechers"},
                new Product(){ Name = "Nike DD9294-001 Downshifter 12 Kadın Koşu Ayakkabısı",Description="",Image="https://productimages.hepsiburada.net/s/259/600-800/110000242660595.jpg", Price = 1069, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Nike"},
                new Product(){ Name = "Nike Air Force 1 '07 Erkek Sneaker Ayakkabı",Description="",Image="https://productimages.hepsiburada.net/s/303/600-800/110000295386353.jpg", Price =999 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Ayakkabı",Brand="Nike"},
                new Product(){ Name = "Nike CI9981-006 Downshifter 10 Erkek Koşu Ayakkabı",Description="",Image="https://productimages.hepsiburada.net/s/42/600-800/10740139294770.jpg", Price =1230 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Nike"},
                new Product(){ Name = "Nike DC3431-033 W Vapor Lite Hc Kadın Tenis Ayakkabı",Description="",Image="https://productimages.hepsiburada.net/s/100/600-800/110000042854602.jpg", Price =1699 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ayakkabı",Brand="Nike"},
                //Ceket

                new Product(){ Name = "Derimod Tom Erkek Deri Ceket",Description="",Image="https://productimages.hepsiburada.net/l/47/600-800/10935514595378.jpg", Price =1699 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ceket",Brand="Derimod"},
                new Product(){ Name = "Jack & Jones Polo Yaka Bomber Ceket",Description="",Image="https://productimages.hepsiburada.net/s/296/600-800/110000285941277.jpg", Price =1740 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Ceket",Brand="Jack & Jones"},
                new Product(){ Name = "Jack & Jones Düz Yaka Normal Kalıp DüzLacivert Erkek Mont",Description="",Image="https://productimages.hepsiburada.net/s/176/600-800/110000140543555.jpg", Price =1239 , ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ceket",Brand="Jack & Jones"},
                new Product(){ Name = "Mavi Suni Kürklü Jean Mont",Description="",Image="https://productimages.hepsiburada.net/l/33/600-800/10407531249714.jpg", Price =879 , ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Ceket",Brand="Mavi"},
                new Product(){ Name = "Derimod St.Moritz Kadın Deri Ceket",Description="",Image="https://productimages.hepsiburada.net/l/47/600-800/10935030153266.jpg", Price =1439, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ceket",Brand="Derimod"},
                new Product(){ Name = "Mavi Kadın Siyah Deri Ceket ",Description="",Image="https://productimages.hepsiburada.net/s/289/600-800/110000277612153.jpg", Price =1659, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Ceket",Brand="Mavi"},

                //Pantolon
                new Product(){ Name = "Loft Nicole Skinny Fit Bayan Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/312/300-400/110000305412528.jpg",Price =429, ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Pantolon",Brand="Loft"},
                new Product(){ Name = "Loft Ricardo Slim Fit Erkek Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/307/300-400/110000299304180.jpg",Price =479, ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Pantolon",Brand="Loft"},
                new Product(){ Name = "Loft Justin Skinny Fit Erkek Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/307/600-800/110000299303125.jpg",Price =389, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Pantolon",Brand="Loft"},
                new Product(){ Name = "LTB Pacası Lastikli Cepli Kahve Rengi Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/258/600-800/110000241688795.jpg",Price =699, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Pantolon",Brand="LTB"},
                new Product(){ Name = "Fabrika Kadın Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/340/300-400/110000347137870.jpg/format:webp",Price =1289, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Pantolon",Brand="Fabrika"},
                new Product(){ Name = "Colin's 759 Lara Orta Bel Dar Kesim Dar Paça Kadın Gri Jean Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/314/600-800/110000308234522.jpg/format:webp",Price =459, ProductAvailable =true,IsHome=true , CategoryId = 2,Type="Pantolon",Brand="Colins"},
                new Product(){ Name = "Colin's Yüksek Bel Dar Paça Süper Slim Slim Fit Koyu Indigo Kadın Jean Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/77/600-800/110000018624493.jpg/format:webp",Price =799, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Pantolon",Brand="Colins"},
                new Product(){ Name = "DeFacto Regular Fit Jogger Pantolon",Description="" ,Image="https://productimages.hepsiburada.net/s/313/600-800/110000306276427.jpg",Price =499, ProductAvailable =true,IsHome=false , CategoryId = 2,Type="Pantolon",Brand="Defacto"},

                /////////////////////////////////////Ev Eşyası
                //Mutfak Araç gereçleri
                new Product(){ Name = "Philips Airfryer HD9252/90 Essential Fritöz",Description = "", Image="https://productimages.hepsiburada.net/s/47/550/10852080910386.jpg", Price =7600  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Mutfak Aletleri",Brand="Philips"},
                new Product(){ Name = "Arzum AR2062-B Airtasty Air Fryer Sıcak Hava Fritözü - Bakır",Description = "", Image="https://productimages.hepsiburada.net/s/290/550/110000278903027.jpg",Price =5600  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Arzum"},
                new Product(){ Name = "Tefal BL1A0D OnTheGO Kişisel Mataralı Blender 0,6 Litre",Description = "", Image="https://productimages.hepsiburada.net/s/18/550/9800185446450.jpg",Price =1499  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Tefal"},
                new Product(){ Name = "Fakir Lucca Q Violet 1000 W Blender Seti",Description = "", Image="https://productimages.hepsiburada.net/s/37/550/10535260553266.jpg",Price =1899  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Mutfak Aletleri",Brand="Fakir"},
                new Product(){ Name = "Philips Daily Collection HD2581/90 Ekmek Kızartma Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/9771236884530.jpg",Price =590  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Philips"},
                new Product(){ Name = "Tefal TT330D Ultra Mini Ekmek Kızartma Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/6/550/9715906674738.jpg",Price =789  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Mutfak Aletleri",Brand="Tefal"},
                new Product(){ Name = "Philips Daily Collection HD9350/90 2200W Su Isıtıcı",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/9754231963698.jpg",Price =389  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Mutfak Aletleri",Brand="Philips"},
                new Product(){ Name = "Karaca Inox Su Isıtıcı Kettle 2203 Paslanmaz Çelik SUS304",Description = "", Image="https://productimages.hepsiburada.net/s/51/550/11060917370930.jpg",Price =568  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Karaca"},
                new Product(){ Name = "Sinbo SSM-2550 Elektrikli Tost Makinesi Büyük Boy",Description = "", Image="https://productimages.hepsiburada.net/s/34/550/10447611035698.jpg",Price =799  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Sinbo"},
                new Product(){ Name = "Tefal GC461B Super Grill XL Izgara ve Tost Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/221/550/110000200585090.jpg",Price =4899  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Mutfak Aletleri",Brand="Tefal"},
                new Product(){ Name = "Sinbo SCM-2957 Elektrikli Cezve Kahve Makinesi Inox",Description = "", Image="https://productimages.hepsiburada.net/s/55/550/11207886831666.jpg",Price =289  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Sinbo"},
                new Product(){ Name = "Arzum OK0013 OKKA Minio Jet Türk Kahvesi Makinesi Bakır",Description = "", Image="https://productimages.hepsiburada.net/s/75/550/110000016497167.jpg",Price =899  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Mutfak Aletleri",Brand="Arzum"},
                //Beyaz Eşya
                new Product(){ Name = "Arçelik 391625 EI 572 Lt Gardırop Tipi No Frost Buzdolabı",Description = "", Image="https://productimages.hepsiburada.net/s/128/550/110000079204914.jpg/format:webp",Price =56799  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik New Star Siyah Cam Ankastre Set",Description = "", Image="https://productimages.hepsiburada.net/s/65/550/110000006700868.jpg",Price =5689  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik 570505 EI 455 Lt No Frost Buzdolabı",Description = "", Image="https://productimages.hepsiburada.net/s/241/550/110000225491075.jpg",Price =15699  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik 10120 MA 1200 Devir 10 kg Çamaşır Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/241/550/110000225809786.jpg",Price =12499  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik 9124 N 1200 Devir 9 kg Çamaşır Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/149/550/110000104119945.jpg",Price =18679  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik 6144 I 4 Programlı Bulaşık Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/114/550/110000062255344.jpg",Price =11049  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Beyaz Eşya",Brand="Arçelik"},
                new Product(){ Name = "Arçelik 6031 3 Programlı Bulaşık Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/135/550/110000087154554.jpg",Price =17599  , ProductAvailable =false,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Bosch"},
                new Product(){ Name = "Bosch KGN86AID1N 631 Lt No-Frost Buzdolabı",Description = "", Image="https://productimages.hepsiburada.net/s/67/550/110000009345227.jpg",Price =25969  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Beyaz Eşya",Brand="Bosch"},
                new Product(){ Name = "Bosch WGA142X1TR 9 kg 1200 Devir Çamaşır Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/58/550/11326513119282.jpg",Price =12459  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Beyaz Eşya",Brand="Bosch"},
                new Product(){ Name = "Bosch SMI25DB01T 5 Programlı Bulaşık Makinesi",Description = "", Image="https://productimages.hepsiburada.net/s/230/550/110000212360285.jpg",Price =15479  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Beyaz Eşya",Brand="Bosch"},
                //Ev Eşyası
                new Product(){ Name = "Bellona Ruby Sağ Uzanmalı Köşe L Koltuk Yataklı Zerowall",Description = "", Image="https://productimages.hepsiburada.net/s/119/550/110000068301503.jpg",Price =21489  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Bellona"},
                new Product(){ Name = "Kilim Mobilya Erciyes Köşe Takımı Versiyon 3 (Üçlü Sağ + Köşe Ünitesi + Ikili Sol)",Description = "", Image="https://productimages.hepsiburada.net/s/338/550/110000344269387.jpg",Price =18799  , ProductAvailable =true,IsHome=false , CategoryId = 3,Type="Ev Eşyaları",Brand="Kilim"},
                new Product(){ Name = "Kaşmir Halı 7/24 Luna Ruby 80X150 cm",Description = "", Image="https://productimages.hepsiburada.net/s/303/550/110000294682152.jpg",Price =697  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Kaşmir"},
                new Product(){ Name = "Kaşmir Halı 7/24 Ethnic Exclusive Floransa 120x180 cm",Description = "", Image="https://productimages.hepsiburada.net/s/156/550/110000113361723.jpg",Price =600  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Kaşmir"},
                new Product(){ Name = "Bellona Telwe Serisi Acılabılır Kelebek Masa 4 Adet Sandalye",Description = "", Image="https://productimages.hepsiburada.net/s/66/550/110000007538681.jpg",Price =4899  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Bellona"},
                new Product(){ Name = "Yataş Bedding Spinal Support Bamboo Pocket Yaylı Yatak - 090 x 190",Description = "", Image="https://productimages.hepsiburada.net/s/146/550/110000100907757.jpg",Price =4899  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Yataş"},
                new Product(){ Name = "Bellona Novado 4 Kapaklı 2 Çekmeceli Gardırop - Beyaz",Description = "", Image="https://productimages.hepsiburada.net/s/104/550/110000047932203.jpg",Price =4299  , ProductAvailable =true,IsHome=true , CategoryId = 3,Type="Ev Eşyaları",Brand="Bellona"},
                ///////////////////// Spor Ürünleri
                //Fitness ürünleri
                new Product(){ Name = "Voit V-Fıt By Voıt Runmate Koşu Bandı",Description = "", Image="https://productimages.hepsiburada.net/s/314/550/110000307579177.jpg",Price =4899  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Fitness Ürünleri",Brand="Voit"},
                new Product(){ Name = "Xiaomi Yesoul S3 Smart Spin Bike Kondisyon Bisikleti",Description = "", Image="https://productimages.hepsiburada.net/s/49/550/10981143773234.jpg",Price =6899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Xiaomi"},
                new Product(){ Name = "Voit U50 Bronze Collection Dikey Bisiklet",Description = "", Image="https://productimages.hepsiburada.net/s/6/550/9728709787698.jpg",Price =2299  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Voit"},
                new Product(){ Name = "Delta 10 - 40 Kg Arası Sertlik Ayarı Yapılabilir Dirençli El Yayı",Description = "", Image="https://productimages.hepsiburada.net/s/25/550/10125665108018.jpg",Price =199  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Fitness Ürünleri",Brand="Delta"},
                new Product(){ Name = "Delta Cosfer CSF-TR03 8 Parça Pilates Seti",Description = "", Image="https://productimages.hepsiburada.net/s/36/550/10505573040178.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Delta"},
                new Product(){ Name = "Delta Konfor Zemin 10 mm Taşıma Askılı Pilates Minderi Yoga Matı",Description = "", Image="https://productimages.hepsiburada.net/s/309/550/110000301971712.jpg",Price =99  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Delta"},
                new Product(){ Name = "Delta Kısa Foam Roller Masaj Köpüğü Köpük Rulo Yuvarlama Köpüğü",Description = "", Image="https://productimages.hepsiburada.net/s/34/550/10449983373362.jpg",Price =99  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Delta"},
                new Product(){ Name = "Delta 102 cm Deluxe Trampolin (40 inç Trambolin)",Description = "", Image="https://productimages.hepsiburada.net/s/77/222-222/110000019536229.jpg",Price =799  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Fitness Ürünleri",Brand="Delta"},
                new Product(){ Name = "Voit El Ayak Çelik Göğüs Yayı Kol Bilek Göğüs Kas Geliştirme Egzersiz Aleti Vücut Geliştirme Seti",Description = "", Image="https://productimages.hepsiburada.net/s/33/550/10403392192562.jpg",Price =289  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Fitness Ürünleri",Brand="Voit"},
                //Kamp Ürünleri
                
                new Product(){ Name = "Quechua Katlanır Kamp Sandalyesi - Mavi - Basic Quechua",Description = "", Image="https://productimages.hepsiburada.net/s/40/550/10655633375282.jpg/format:webp",Price =289  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Kamp",Brand="Quechua"},
                new Product(){ Name = "Quechua Tabure Katlanır Kamp Balıkçı Outdoor Sandalye",Description = "", Image="https://productimages.hepsiburada.net/s/40/550/10655633047602.jpg",Price =199  , ProductAvailable =false,IsHome=false , CategoryId = 4,Type="Kamp",Brand="Quechua"},
                new Product(){ Name = "Quechua Campout Family Çadır",Description = "", Image="https://productimages.hepsiburada.net/s/69/550/110000010831867.jpg",Price =1899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Kamp",Brand="Quechua"},
                new Product(){ Name = "Voit Çadır",Description = "", Image="https://productimages.hepsiburada.net/s/76/550/110000017932920.jpg",Price =2899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Kamp",Brand="Voit"},
                new Product(){ Name = "Quechua Orcamp Katlanır Çantalı Ateş Üstü Kamp Izgarası (Küçük Boy)",Description = "", Image="https://productimages.hepsiburada.net/s/124/550/110000074433349.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Kamp",Brand="Quechua"},
                new Product(){ Name = "Wander Körüklü Dağcı Siyah Sırt Çantası",Description = "", Image="https://productimages.hepsiburada.net/s/24/550/10093043580978.jpg",Price =499  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Kamp",Brand="Wander"},
                new Product(){ Name = "Quechua Kamp Uyku Tulumu - 10°c - Petrol Yeşili- Arpenaz",Description = "", Image="https://productimages.hepsiburada.net/s/183/550/110000146896363.jpg",Price =559  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Kamp",Brand="Quechua"},
               // Spor ürünleri
                new Product(){ Name = "Adidas Rihla Clb Futbol Topu H57778 Renkli",Description = "", Image="https://productimages.hepsiburada.net/s/226/550/110000206519091.jpg",Price =499  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Spor",Brand="Adidas"},
                new Product(){ Name = "Adidas Neymar Forması 3 lü Set",Description = "", Image="https://productimages.hepsiburada.net/s/266/550/110000250802131.jpg",Price =1899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Spor",Brand="Adidas"},
                new Product(){ Name = "Delta Team Kaleci Eldiveni",Description = "", Image="https://productimages.hepsiburada.net/s/26/550/10165973090354.jpg",Price =199  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Spor",Brand="Delta"},
                new Product(){ Name = "Delta Aventura Mavi Masa Tenisi Masası 2 Raket 6 Top File Demir",Description = "", Image="https://productimages.hepsiburada.net/s/38/550/10600881127474.jpg",Price =4899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Spor",Brand="Delta"},
                new Product(){ Name = "Delta Çantalı 100 adet Turuncu Masa Tenisi Topu (Pinpon Topu)",Description = "", Image="https://productimages.hepsiburada.net/s/5/550/9686736175154.jpg",Price =129  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Spor",Brand="Delta"},
                new Product(){ Name = "Voit Guard 2 Star Masa Tenisi Pinpon Raketi",Description = "", Image="https://productimages.hepsiburada.net/s/13/550/9014639427634.jpg",Price =99  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Spor",Brand="Voit"},
                new Product(){ Name = "Spalding TF-150 Basketbol Topu Perform No:7 Fiba Logo",Description = "", Image="https://productimages.hepsiburada.net/s/107/550/110000050731493.jpg",Price =899  , ProductAvailable =true,IsHome=false , CategoryId = 4,Type="Spor",Brand="Spalding"},
                new Product(){ Name = "Adidas Donovan Mitchell Issue 4 Basketbol Topu",Description = "", Image="https://productimages.hepsiburada.net/s/285/550/110000274470426.jpg",Price =1599  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Spor",Brand="Adidas"},
                new Product(){ Name = "Mikasa V200W FIVB Onaylı 5 Numara Voleybol Maç Topu",Description = "", Image="https://productimages.hepsiburada.net/s/35/550/10470241665074.jpg",Price =699  , ProductAvailable =true,IsHome=true , CategoryId = 4,Type="Spor",Brand="Mikasa"},

                /////////////// Kişisel bakım
                // Saç Bakım
                new Product(){ Name = "Head & Shoulders Spor Ferahlığı Kepeğe Karşı Karşı Etkili",Description = "", Image="https://productimages.hepsiburada.net/s/163/550/110000121953840.jpg",Price =56  , ProductAvailable =true,IsHome=true , CategoryId = 5,Type="Saç Bakım",Brand="Head & Shoulders"},
                new Product(){ Name = "Head & Shoulders Şampuan Limon Ferahlığı 350 ml",Description = "", Image="https://productimages.hepsiburada.net/s/186/550/110000150696289.jpg",Price =54  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Saç Bakım",Brand="Head & Shoulders"},
                new Product(){ Name = "Elidor Superblend 2'si 1 Arada Şampuan ve Saç Bakım Kremi",Description = "", Image="https://productimages.hepsiburada.net/s/206/550/110000182743981.jpg",Price =46  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Saç Bakım",Brand="Elidor"},
                new Product(){ Name = "Clear Women Kepeğe Karşı Etkili Şampuan Saç Dökülmesine Karşı Zencefil Özü 485 ml + 180 ml",Description = "", Image="https://productimages.hepsiburada.net/s/229/550/110000210986308.jpg",Price =99  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Saç Bakım",Brand="Clear"},
                new Product(){ Name = "Head & Shoulders Dermaxpro Yatıştırıcı Etki Aloe Içeren Kepek Karşıtı Saç Derisi Balsamı",Description = "", Image="https://productimages.hepsiburada.net/s/343/550/110000350182835.jpg/format:webp",Price =79  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Saç Bakım",Brand="Head & Shoulders"},
                new Product(){ Name = "Head & Shoulders Clinical Kuru Saç Derisini Kurtarma Saç Kremi 265 ml",Description = "", Image="https://productimages.hepsiburada.net/s/106/550/110000049616752.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Saç Bakım",Brand="Head & Shoulders"},
                //Ağız Bakım
                new Product(){ Name = "Sensodyne Tam Koruma Beyazlatıcı Diş Macunu 50 Ml. 6'lı Set",Description = "", Image="https://productimages.hepsiburada.net/s/276/550/110000262542415.jpg",Price =189  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Ağız Bakım",Brand="Sensodyne"},
                new Product(){ Name = "Colgate Total Profesyonel Diş Eti Diş Macunu 50 ml x 2 Adet ",Description = "", Image="https://productimages.hepsiburada.net/s/289/550/110000278270411.jpg",Price =199  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Ağız Bakım",Brand="Colgate"},
                new Product(){ Name = "Oral-B D100 Vitality Cross Action Şarjlı Diş Fırçası - Siyah",Description = "", Image="https://productimages.hepsiburada.net/s/39/550/10642256396338.jpg",Price =699  , ProductAvailable =true,IsHome=true , CategoryId = 5,Type="Ağız Bakım",Brand="Oral-B"},
                new Product(){ Name = "Colgate Minions Çürüklere Karşı Etkili Çocuk Diş Macunu 50 ml",Description = "", Image="https://productimages.hepsiburada.net/s/65/550/110000006695060.jpg",Price =29  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Ağız Bakım",Brand="Colgate"},
                new Product(){ Name = "Colgate Plax Taze Nane Ferahlığı Ağız Bakım Suyu 250 ml",Description = "", Image="https://productimages.hepsiburada.net/s/65/550/110000006695079.jpg",Price =139  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Ağız Bakım",Brand="Colgate"},
                //Parfüm
                
                
                new Product(){ Name = "Avon Celebre ve Pur Blanca Kadın Parfüm Seti",Description = "", Image="https://productimages.hepsiburada.net/s/253/550/110000235445469.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Parfüm",Brand="Avon"},
                new Product(){ Name = "Avon Musk+ Mineralis Erkek Edt 75 ml",Description = "", Image="https://productimages.hepsiburada.net/s/354/550/110000363111529.jpg",Price =499  , ProductAvailable =true,IsHome=true , CategoryId = 5,Type="Parfüm",Brand="Avon"},
                new Product(){ Name = "Avon Full Speed Edt 75 Ml Erkek Parfüm",Description = "", Image="https://productimages.hepsiburada.net/s/72/550/110000014048705.jpg",Price =199  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Parfüm",Brand="Avon"},
                new Product(){ Name = "Avon Little Black Dress Kadın Parfüm Losyon Rollon ve Vücut Spreyi Seti",Description = "", Image="https://productimages.hepsiburada.net/s/39/550/10645720662066.jpg",Price =699  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Parfüm",Brand="Avon"},

                //Makyaj
                new Product(){ Name = "Flormar Dudak Kalemi Matte Color Lipstick Jumbo Kalın Kalem Ruj Waterproof 12'li Set",Description = "", Image="https://productimages.hepsiburada.net/s/294/550/110000283683965.jpg",Price =299  , ProductAvailable =true,IsHome=true , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Pretty Essantial Lipstick - Parlak Ruj Tea Rose NO:007",Description = "", Image="https://productimages.hepsiburada.net/s/28/550/10240330924082.jpg",Price =99  , ProductAvailable =true,IsHome=true , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Flormar-Maskara - Big N Bold Mascara 001 Volume",Description = "", Image="https://productimages.hepsiburada.net/s/258/550/110000241768795.jpg",Price =199  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Yüksek Kapatıcı Su Bazlı Yarı Mat Fondöten ",Description = "", Image="https://productimages.hepsiburada.net/s/1/550/9523056082994.jpg",Price =199  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Göz Kalemi - Ultra Siyah Eyeliner 3 Lü Avantaj",Description = "", Image="https://productimages.hepsiburada.net/s/43/550/10785571766322.jpg/format:webp",Price =49  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Jelly Look Nail Enamel Oje L23 Stunning Red",Description = "", Image="https://productimages.hepsiburada.net/s/37/550/10571640963122.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar By Pretty Matte Lıpstıck 70 Perfect For Date",Description = "", Image="https://productimages.hepsiburada.net/s/50/550/11049885761586.jpg",Price =79  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar - Oje - French Manicure Set",Description = "", Image="https://productimages.hepsiburada.net/s/1/550/9523061784626.jpg",Price =199  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Yoğun Renk Veren Yarı Mat ve Sedefli 10'lu Far Paleti",Description = "", Image="https://productimages.hepsiburada.net/s/22/550/9950587191346.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},
                new Product(){ Name = "Flormar Doğal Işıltı Veren Likit Aydınlatıcı & Makyaj Bazı",Description = "", Image="https://productimages.hepsiburada.net/s/22/550/9950588207154.jpg",Price =299  , ProductAvailable =true,IsHome=false , CategoryId = 5,Type="Makyaj",Brand="Flormar"},

                ///////////////////////////////////////////// Film Müzik Kitap
                ///Çizgi Film
                 new Product(){ Name = "Pamuk Prenses (Good Times) ( DVD )",Description = "", Image="https://productimages.hepsiburada.net/s/8/550/8934755762226.jpg",Price =39  , ProductAvailable =true,IsHome=true , CategoryId = 6,Type="Çizgi Film",Brand=""},
                 new Product(){ Name = "The Smurfs 2 (Şirinler 2) (3D Blu-Ray Disc)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8820047904818.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Çizgi Film",Brand=""},
                 new Product(){ Name = "A Cat in Paris (Hırsız Kedi Paris'te)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8900098883634.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Çizgi Film",Brand=""},
                 new Product(){ Name = "Sevimli Canavarlar (Monsters, Inc.) ( VCD )",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8913544216626.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Çizgi Film",Brand=""},
                 new Product(){ Name = "Brother Bear 2 (Ayı Kardeş 2)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8854342271026.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Çizgi Film",Brand=""},
                 new Product(){ Name = "Tarzan (DVD)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8851123437618.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Çizgi Film",Brand=""},

                 //Film
                 new Product(){ Name = "Gravity (Yerçekimi) (DVD)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8914619072562.jpg",Price =39  , ProductAvailable =true,IsHome=true , CategoryId = 6,Type="Film",Brand=""},
                 new Product(){ Name = "Hereafter (Öteki Dünya)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8929768898610.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Film",Brand=""},
                 new Product(){ Name = "Edison (Blu-Ray Disc)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8854855090226.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Film",Brand=""},
                 new Product(){ Name = "Escape Plan (Kaçış Planı) (DVD)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8851122225202.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Film",Brand=""},
                 new Product(){ Name = "Adam Resurrected (Diriliş)",Description = "", Image="https://productimages.hepsiburada.net/s/7/550/8858890960946.jpg",Price =39  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Film",Brand=""},

                 //Kitap
                 new Product(){ Name = "Ne İçin Varsan Onun İçin Yaşa - Hikmet Anıl Öztekin",Description = "", Image="https://productimages.hepsiburada.net/s/125/550/110000075577551.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Kitap",Brand=""},
                 new Product(){ Name = "Osmanlı’yı Yeniden Keşfetmek - İlber Ortaylı",Description = "", Image="https://productimages.hepsiburada.net/s/348/550/110000356827253.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Kitap",Brand=""},
                 new Product(){ Name = "Aşıklara Yer Yok - Tarık Tufan",Description = "", Image="https://productimages.hepsiburada.net/s/348/550/110000356797331.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Kitap",Brand=""},
                 new Product(){ Name = "Kırmızı Pelerin - Gülseren Budayıcıoğlu",Description = "", Image="https://productimages.hepsiburada.net/s/310/550/110000303631107.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Kitap",Brand=""},
                 new Product(){ Name = "Kayıp Kelimeler Sözlüğü - Pip Williams",Description = "", Image="https://productimages.hepsiburada.net/s/314/550/110000307337065.jpg",Price =59  , ProductAvailable =true,IsHome=true , CategoryId = 6,Type="Kitap",Brand=""},
                 new Product(){ Name = "Her Şey Vaktini Bekler - Şems’in Öğrencisi Olmak - Hakan Mengüç",Description = "", Image="https://productimages.hepsiburada.net/s/261/550/110000245290471.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Kitap",Brand=""},
                 
                 //Müzik
                 new Product(){ Name = "Neşet Ertaş - Zahidem / Gönül Dağı - Plak",Description = "", Image="https://productimages.hepsiburada.net/s/42/550/10725619367986.jpg",Price =159  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand=""},
                 new Product(){ Name = "61 Tuşlu ( 5 Oktav) Org",Description = "", Image="https://productimages.hepsiburada.net/s/56/550/11267935567922.jpg",Price =4559  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand="Jwin"},
                 new Product(){ Name = "Admira Alba ADMI0200S Klasik Gitar (Mat Cilalı)",Description = "", Image="https://productimages.hepsiburada.net/s/307/550/110000300107081.jpg",Price =7859  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand="Admira"},
                 new Product(){ Name = "Ertan Sert - Atatürk'ün Sevdiği Şarkılar (Plak)",Description = "", Image="https://productimages.hepsiburada.net/s/6/550/9706677239858.jpg",Price =59  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand=""},
                 new Product(){ Name = "GDL Retro Çanta Pikap T317 - Vip (Dahili Şarjlı)",Description = "", Image="https://productimages.hepsiburada.net/s/44/550/10804274790450.jpg",Price =1859  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand="Gdl"},
                 new Product(){ Name = "Bergen - Acıların Kadını (Plak)",Description = "", Image="https://productimages.hepsiburada.net/s/237/550/110000220761273.jpg",Price =159  , ProductAvailable =true,IsHome=false , CategoryId = 6,Type="Müzik",Brand=""},

            };

            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }

            context.SaveChanges();

            base.Seed(context);
        }
    }
}