// <auto-generated />
namespace E_Commerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ECommercedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ECommercedb));
        
        string IMigrationMetadata.Id
        {
            get { return "202301051411533_E-Commerce.db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
